
import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import ClientProvider from "./ClientProvider";
import { Header } from "@/components/header/Header";
import { Navbar } from "@/components/navbar/navbar";
import { ThemeProvider } from "@/components/theme-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Azi Management System",
  description: "Generated by Azi Management System",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)} suppressHydrationWarning={true}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClientProvider>
            <div className="flex min-h-screen flex-col">
              <div className="grid grid-cols-12 gap-4">
                <div className=" col-start-1 col-span-2"> <Navbar /></div>
                <div className=" col-start-3 col-span-12 "><Header />
                  {children}
                </div>
              </div>
            </div>
          </ClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
